# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-09-25 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0002_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='razones',
            field=models.TextField(null=True),
        ),
    ]
